### ISSUE TITLE
About typespaces.p

### ISSUE THREAD

**Issue by tianyu-su** [mvasil/fashion-compatibility#19]
https://github.com/mvasil/fashion-compatibility/blob/299b426e38b92b4441534e025bf84caa0ea3155b/polyvore_outfits.py#L65
Hi, thanks for your code. I however have a question about how to generate a file of typesapces.p at first time. Above on that ref, the  function of the load_typespaces should provide a original typespaces.p although I want to get a new typespaces.p at first.
So, how I can generate the file when the typespaces.p file is not saved in the disk.
Looking forward to your reply.

**Comment by marzooq-unbxd** [comment]
Can you help me with this @tianyu-su 
I am trying to use the already trained model in order to confirm its benchmark results.
But i dont know how many typespaces to use , I only got 
```
'tops', 'jewellery', 'bottoms', 'bags', 'shoes', 'hats', 'accessories', 'all-body', 'outerwear', 'sunglasses', 'scarves'
```
as categories in the polyvore dataset I used.
I am not able to  map a new product to the typespaces , since I cant get the list of all typespaces.
